version: '3.8'

services:
  webapi:
    build:
      context: ./dotnet-api
      dockerfile: Dockerfile
    ports:
      - "5178:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  angular:
    build:
      context: ./angularUI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"